version: "3.9"
services:
    app:
        build: .
        ports:
            - "8000:8000"
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./app:/app
        depends_on: 
            - db
        environment: 
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=randompassword123

    db:
        image: postgres:10-alpine
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=randompassword123